package apcon;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IUBusqueda.java
 *
 * Created on 20/04/2010, 12:31:53 PM
 */

/**
 *
 * @author Andres
 */
public class IUBusqueda extends JFrame{

    private Person person;
    private GestorGestionarProyecto gestionar;
    String query;

    /** Creates new form IUBusqueda */
    public IUBusqueda() throws SQLException, ClassNotFoundException
    {
        person = new Person();
        gestionar = new GestorGestionarProyecto();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanelPropiedadesProyecto = new javax.swing.JPanel();
        jPanelDescripcion = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneDescripcion = new javax.swing.JTextPane();
        jLabelNombreProyecto = new javax.swing.JLabel();
        jLabelNombreAutor = new javax.swing.JLabel();
        jLabelApellidoAutor = new javax.swing.JLabel();
        jLabelIDAutor = new javax.swing.JLabel();
        jLabelPlanta = new javax.swing.JLabel();
        jLabelSubSistema = new javax.swing.JLabel();
        jLabelEquipo = new javax.swing.JLabel();
        jTextFieldPlanta = new javax.swing.JTextField();
        jTextFieldSubSistema = new javax.swing.JTextField();
        jTextFieldEquipo = new javax.swing.JTextField();
        jTextFieldIDAutor = new javax.swing.JTextField();
        jTextFieldNombreProyecto = new javax.swing.JTextField();
        jTextFieldNombreAutor = new javax.swing.JTextField();
        jTextFieldApellidoAutor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxWeibull = new javax.swing.JCheckBox();
        jCheckBoxSFR = new javax.swing.JCheckBox();
        jButtonEliminar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jPanelBuscador = new javax.swing.JPanel();
        jLabelIDAutorB = new javax.swing.JLabel();
        jLabelNombreProyectoB = new javax.swing.JLabel();
        jTextFieldIDAutorB = new javax.swing.JTextField();
        jTextFieldNombreProyectoB = new javax.swing.JTextField();
        jButtonBuscar1 = new javax.swing.JButton();
        jButtonBuscar2 = new javax.swing.JButton();
        jPanelProyectos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProyectos = new javax.swing.JList();
        jButtonCargar = new javax.swing.JButton();

        jProgressBar1.setName("jProgressBar1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        setResizable(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(apcon.APCONApp.class).getContext().getResourceMap(IUBusqueda.class);
        jPanelPropiedadesProyecto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanelPropiedadesProyecto.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanelPropiedadesProyecto.border.titleFont"), resourceMap.getColor("jPanelPropiedadesProyecto.border.titleColor"))); // NOI18N
        jPanelPropiedadesProyecto.setName("jPanelPropiedadesProyecto"); // NOI18N

        jPanelDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanelDescripcion.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanelDescripcion.border.titleFont"), resourceMap.getColor("jPanelDescripcion.border.titleColor"))); // NOI18N
        jPanelDescripcion.setName("jPanelDescripcion"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextPaneDescripcion.setBackground(resourceMap.getColor("jTextPaneDescripcion.background")); // NOI18N
        jTextPaneDescripcion.setBorder(new javax.swing.border.MatteBorder(null));
        jTextPaneDescripcion.setFont(resourceMap.getFont("jTextPaneDescripcion.font")); // NOI18N
        jTextPaneDescripcion.setToolTipText(resourceMap.getString("jTextPaneDescripcion.toolTipText")); // NOI18N
        jTextPaneDescripcion.setEnabled(false);
        jTextPaneDescripcion.setName("jTextPaneDescripcion"); // NOI18N
        jTextPaneDescripcion.setNextFocusableComponent(jButtonSalvar);
        jTextPaneDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPaneDescripcionKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTextPaneDescripcion);

        javax.swing.GroupLayout jPanelDescripcionLayout = new javax.swing.GroupLayout(jPanelDescripcion);
        jPanelDescripcion.setLayout(jPanelDescripcionLayout);
        jPanelDescripcionLayout.setHorizontalGroup(
            jPanelDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDescripcionLayout.setVerticalGroup(
            jPanelDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescripcionLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelNombreProyecto.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jLabelNombreProyecto.setText(resourceMap.getString("jLabelNombreProyecto.text")); // NOI18N
        jLabelNombreProyecto.setName("jLabelNombreProyecto"); // NOI18N

        jLabelNombreAutor.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jLabelNombreAutor.setText(resourceMap.getString("jLabelNombreAutor.text")); // NOI18N
        jLabelNombreAutor.setName("jLabelNombreAutor"); // NOI18N

        jLabelApellidoAutor.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jLabelApellidoAutor.setText(resourceMap.getString("jLabelApellidoAutor.text")); // NOI18N
        jLabelApellidoAutor.setName("jLabelApellidoAutor"); // NOI18N

        jLabelIDAutor.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jLabelIDAutor.setText(resourceMap.getString("jLabelIDAutor.text")); // NOI18N
        jLabelIDAutor.setName("jLabelIDAutor"); // NOI18N

        jLabelPlanta.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jLabelPlanta.setText(resourceMap.getString("jLabelPlanta.text")); // NOI18N
        jLabelPlanta.setName("jLabelPlanta"); // NOI18N

        jLabelSubSistema.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jLabelSubSistema.setText(resourceMap.getString("jLabelSubSistema.text")); // NOI18N
        jLabelSubSistema.setName("jLabelSubSistema"); // NOI18N

        jLabelEquipo.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jLabelEquipo.setText(resourceMap.getString("jLabelEquipo.text")); // NOI18N
        jLabelEquipo.setName("jLabelEquipo"); // NOI18N

        jTextFieldPlanta.setFont(resourceMap.getFont("jTextPaneDescripcion.font")); // NOI18N
        jTextFieldPlanta.setText(resourceMap.getString("jTextFieldPlanta.text")); // NOI18N
        jTextFieldPlanta.setToolTipText(resourceMap.getString("jTextFieldPlanta.toolTipText")); // NOI18N
        jTextFieldPlanta.setEnabled(false);
        jTextFieldPlanta.setName("jTextFieldPlanta"); // NOI18N
        jTextFieldPlanta.setNextFocusableComponent(jTextFieldSubSistema);
        jTextFieldPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlantaActionPerformed(evt);
            }
        });
        jTextFieldPlanta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPlantaKeyTyped(evt);
            }
        });

        jTextFieldSubSistema.setFont(resourceMap.getFont("jTextPaneDescripcion.font")); // NOI18N
        jTextFieldSubSistema.setText(resourceMap.getString("jTextFieldSubSistema.text")); // NOI18N
        jTextFieldSubSistema.setToolTipText(resourceMap.getString("jTextFieldSubSistema.toolTipText")); // NOI18N
        jTextFieldSubSistema.setEnabled(false);
        jTextFieldSubSistema.setName("jTextFieldSubSistema"); // NOI18N
        jTextFieldSubSistema.setNextFocusableComponent(jTextFieldEquipo);
        jTextFieldSubSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSubSistemaActionPerformed(evt);
            }
        });
        jTextFieldSubSistema.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSubSistemaKeyTyped(evt);
            }
        });

        jTextFieldEquipo.setFont(resourceMap.getFont("jTextPaneDescripcion.font")); // NOI18N
        jTextFieldEquipo.setText(resourceMap.getString("jTextFieldEquipo.text")); // NOI18N
        jTextFieldEquipo.setToolTipText(resourceMap.getString("jTextFieldEquipo.toolTipText")); // NOI18N
        jTextFieldEquipo.setEnabled(false);
        jTextFieldEquipo.setName("jTextFieldEquipo"); // NOI18N
        jTextFieldEquipo.setNextFocusableComponent(jTextPaneDescripcion);
        jTextFieldEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEquipoActionPerformed(evt);
            }
        });
        jTextFieldEquipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEquipoKeyTyped(evt);
            }
        });

        jTextFieldIDAutor.setFont(resourceMap.getFont("jTextPaneDescripcion.font")); // NOI18N
        jTextFieldIDAutor.setToolTipText(resourceMap.getString("jTextFieldIDAutor.toolTipText")); // NOI18N
        jTextFieldIDAutor.setEnabled(false);
        jTextFieldIDAutor.setName("jTextFieldIDAutor"); // NOI18N
        jTextFieldIDAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDAutorActionPerformed(evt);
            }
        });
        jTextFieldIDAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDAutorKeyTyped(evt);
            }
        });

        jTextFieldNombreProyecto.setFont(resourceMap.getFont("jTextPaneDescripcion.font")); // NOI18N
        jTextFieldNombreProyecto.setToolTipText(resourceMap.getString("jTextFieldNombreProyecto.toolTipText")); // NOI18N
        jTextFieldNombreProyecto.setEnabled(false);
        jTextFieldNombreProyecto.setName("jTextFieldNombreProyecto"); // NOI18N
        jTextFieldNombreProyecto.setNextFocusableComponent(jTextFieldNombreAutor);
        jTextFieldNombreProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreProyectoActionPerformed(evt);
            }
        });
        jTextFieldNombreProyecto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreProyectoKeyTyped(evt);
            }
        });

        jTextFieldNombreAutor.setFont(resourceMap.getFont("jTextPaneDescripcion.font")); // NOI18N
        jTextFieldNombreAutor.setToolTipText(resourceMap.getString("jTextFieldNombreAutor.toolTipText")); // NOI18N
        jTextFieldNombreAutor.setEnabled(false);
        jTextFieldNombreAutor.setName("jTextFieldNombreAutor"); // NOI18N
        jTextFieldNombreAutor.setNextFocusableComponent(jTextFieldApellidoAutor);
        jTextFieldNombreAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreAutorActionPerformed(evt);
            }
        });
        jTextFieldNombreAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreAutorKeyTyped(evt);
            }
        });

        jTextFieldApellidoAutor.setFont(resourceMap.getFont("jTextPaneDescripcion.font")); // NOI18N
        jTextFieldApellidoAutor.setToolTipText(resourceMap.getString("jTextFieldApellidoAutor.toolTipText")); // NOI18N
        jTextFieldApellidoAutor.setEnabled(false);
        jTextFieldApellidoAutor.setName("jTextFieldApellidoAutor"); // NOI18N
        jTextFieldApellidoAutor.setNextFocusableComponent(jTextFieldPlanta);
        jTextFieldApellidoAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoAutorActionPerformed(evt);
            }
        });
        jTextFieldApellidoAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidoAutorKeyTyped(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel1.border.titleFont"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jCheckBoxWeibull.setFont(resourceMap.getFont("jCheckBoxWeibull.font")); // NOI18N
        jCheckBoxWeibull.setText(resourceMap.getString("jCheckBoxWeibull.text")); // NOI18N
        jCheckBoxWeibull.setEnabled(false);
        jCheckBoxWeibull.setName("jCheckBoxWeibull"); // NOI18N

        jCheckBoxSFR.setFont(resourceMap.getFont("jCheckBoxSFR.font")); // NOI18N
        jCheckBoxSFR.setText(resourceMap.getString("jCheckBoxSFR.text")); // NOI18N
        jCheckBoxSFR.setEnabled(false);
        jCheckBoxSFR.setName("jCheckBoxSFR"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxWeibull)
                    .addComponent(jCheckBoxSFR))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxWeibull)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxSFR)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelPropiedadesProyectoLayout = new javax.swing.GroupLayout(jPanelPropiedadesProyecto);
        jPanelPropiedadesProyecto.setLayout(jPanelPropiedadesProyectoLayout);
        jPanelPropiedadesProyectoLayout.setHorizontalGroup(
            jPanelPropiedadesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPropiedadesProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPropiedadesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNombreAutor)
                    .addComponent(jLabelApellidoAutor)
                    .addComponent(jLabelIDAutor)
                    .addComponent(jLabelNombreProyecto)
                    .addComponent(jLabelPlanta)
                    .addComponent(jLabelSubSistema)
                    .addComponent(jLabelEquipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPropiedadesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPropiedadesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldNombreProyecto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldNombreAutor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldApellidoAutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPropiedadesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldEquipo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldSubSistema, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldPlanta, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldIDAutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPropiedadesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelPropiedadesProyectoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldApellidoAutor, jTextFieldEquipo, jTextFieldIDAutor, jTextFieldNombreAutor, jTextFieldNombreProyecto, jTextFieldPlanta, jTextFieldSubSistema});

        jPanelPropiedadesProyectoLayout.setVerticalGroup(
            jPanelPropiedadesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPropiedadesProyectoLayout.createSequentialGroup()
                .addGroup(jPanelPropiedadesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPropiedadesProyectoLayout.createSequentialGroup()
                        .addComponent(jPanelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPropiedadesProyectoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanelPropiedadesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombreProyecto)
                            .addComponent(jTextFieldNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanelPropiedadesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombreAutor)
                            .addComponent(jTextFieldNombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPropiedadesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelApellidoAutor)
                            .addComponent(jTextFieldApellidoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanelPropiedadesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIDAutor)
                            .addComponent(jTextFieldIDAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanelPropiedadesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPlanta)
                            .addComponent(jTextFieldPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanelPropiedadesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSubSistema)
                            .addComponent(jTextFieldSubSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanelPropiedadesProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEquipo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPropiedadesProyectoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldApellidoAutor, jTextFieldEquipo, jTextFieldIDAutor, jTextFieldNombreAutor, jTextFieldNombreProyecto, jTextFieldPlanta, jTextFieldSubSistema});

        jButtonEliminar.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jButtonEliminar.setText(resourceMap.getString("jButtonEliminar.text")); // NOI18N
        jButtonEliminar.setToolTipText(resourceMap.getString("jButtonEliminar.toolTipText")); // NOI18N
        jButtonEliminar.setName("jButtonEliminar"); // NOI18N
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminar(evt);
            }
        });

        jButtonModificar.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jButtonModificar.setText(resourceMap.getString("jButtonModificar.text")); // NOI18N
        jButtonModificar.setToolTipText(resourceMap.getString("jButtonModificar.toolTipText")); // NOI18N
        jButtonModificar.setName("jButtonModificar"); // NOI18N
        jButtonModificar.setNextFocusableComponent(jTextFieldNombreProyecto);
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificar(evt);
            }
        });

        jButtonCancelar.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jButtonCancelar.setText(resourceMap.getString("jButtonCancelar.text")); // NOI18N
        jButtonCancelar.setToolTipText(resourceMap.getString("jButtonCancelar.toolTipText")); // NOI18N
        jButtonCancelar.setName("jButtonCancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelar(evt);
            }
        });

        jButtonSalvar.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jButtonSalvar.setText(resourceMap.getString("jButtonSalvar.text")); // NOI18N
        jButtonSalvar.setToolTipText(resourceMap.getString("jButtonSalvar.toolTipText")); // NOI18N
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.setName("jButtonSalvar"); // NOI18N
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalvar(evt);
            }
        });

        jPanelBuscador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanelBuscador.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanelBuscador.border.titleFont"), resourceMap.getColor("jPanelBuscador.border.titleColor"))); // NOI18N
        jPanelBuscador.setName("jPanelBuscador"); // NOI18N

        jLabelIDAutorB.setFont(resourceMap.getFont("jLabelNombreProyectoB.font")); // NOI18N
        jLabelIDAutorB.setText(resourceMap.getString("jLabelIDAutorB.text")); // NOI18N
        jLabelIDAutorB.setName("jLabelIDAutorB"); // NOI18N

        jLabelNombreProyectoB.setFont(resourceMap.getFont("jLabelNombreProyectoB.font")); // NOI18N
        jLabelNombreProyectoB.setText(resourceMap.getString("jLabelNombreProyectoB.text")); // NOI18N
        jLabelNombreProyectoB.setName("jLabelNombreProyectoB"); // NOI18N

        jTextFieldIDAutorB.setFont(resourceMap.getFont("jTextPaneDescripcion.font")); // NOI18N
        jTextFieldIDAutorB.setToolTipText(resourceMap.getString("jTextFieldIDAutorB.toolTipText")); // NOI18N
        jTextFieldIDAutorB.setName("jTextFieldIDAutorB"); // NOI18N
        jTextFieldIDAutorB.setNextFocusableComponent(jButtonBuscar1);
        jTextFieldIDAutorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDAutorBActionPerformed(evt);
            }
        });
        jTextFieldIDAutorB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDAutorBKeyTyped(evt);
            }
        });

        jTextFieldNombreProyectoB.setFont(resourceMap.getFont("jTextPaneDescripcion.font")); // NOI18N
        jTextFieldNombreProyectoB.setToolTipText(resourceMap.getString("jTextFieldNombreProyectoB.toolTipText")); // NOI18N
        jTextFieldNombreProyectoB.setName("jTextFieldNombreProyectoB"); // NOI18N
        jTextFieldNombreProyectoB.setNextFocusableComponent(jButtonBuscar2);
        jTextFieldNombreProyectoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreProyectoBActionPerformed(evt);
            }
        });
        jTextFieldNombreProyectoB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreProyectoBKeyTyped(evt);
            }
        });

        jButtonBuscar1.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jButtonBuscar1.setText(resourceMap.getString("jButtonBuscar1.text")); // NOI18N
        jButtonBuscar1.setToolTipText(resourceMap.getString("jButtonBuscar1.toolTipText")); // NOI18N
        jButtonBuscar1.setName("jButtonBuscar1"); // NOI18N
        jButtonBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscar1(evt);
            }
        });

        jButtonBuscar2.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jButtonBuscar2.setText(resourceMap.getString("jButtonBuscar2.text")); // NOI18N
        jButtonBuscar2.setToolTipText(resourceMap.getString("jButtonBuscar2.toolTipText")); // NOI18N
        jButtonBuscar2.setName("jButtonBuscar2"); // NOI18N
        jButtonBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscar2(evt);
            }
        });

        jPanelProyectos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanelProyectos.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanelProyectos.border.titleFont"), resourceMap.getColor("jPanelProyectos.border.titleColor"))); // NOI18N
        jPanelProyectos.setName("jPanelProyectos"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jListProyectos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jListProyectos.setFont(resourceMap.getFont("jTextPaneDescripcion.font")); // NOI18N
        jListProyectos.setToolTipText(resourceMap.getString("jListProyectos.toolTipText")); // NOI18N
        jListProyectos.setName("jListProyectos"); // NOI18N
        jListProyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listaProyectos(evt);
            }
        });
        jScrollPane1.setViewportView(jListProyectos);

        javax.swing.GroupLayout jPanelProyectosLayout = new javax.swing.GroupLayout(jPanelProyectos);
        jPanelProyectos.setLayout(jPanelProyectosLayout);
        jPanelProyectosLayout.setHorizontalGroup(
            jPanelProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProyectosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelProyectosLayout.setVerticalGroup(
            jPanelProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProyectosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelBuscadorLayout = new javax.swing.GroupLayout(jPanelBuscador);
        jPanelBuscador.setLayout(jPanelBuscadorLayout);
        jPanelBuscadorLayout.setHorizontalGroup(
            jPanelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIDAutorB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNombreProyectoB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldIDAutorB)
                    .addComponent(jTextFieldNombreProyectoB, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBuscar2)
                    .addComponent(jButtonBuscar1))
                .addGap(18, 18, 18)
                .addComponent(jPanelProyectos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBuscadorLayout.setVerticalGroup(
            jPanelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscadorLayout.createSequentialGroup()
                .addGroup(jPanelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanelBuscadorLayout.createSequentialGroup()
                        .addComponent(jButtonBuscar1)
                        .addGap(6, 6, 6)
                        .addComponent(jButtonBuscar2))
                    .addGroup(jPanelBuscadorLayout.createSequentialGroup()
                        .addComponent(jTextFieldIDAutorB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldNombreProyectoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBuscadorLayout.createSequentialGroup()
                        .addComponent(jLabelIDAutorB)
                        .addGap(15, 15, 15)
                        .addComponent(jLabelNombreProyectoB))
                    .addComponent(jPanelProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonCargar.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jButtonCargar.setText(resourceMap.getString("jButtonCargar.text")); // NOI18N
        jButtonCargar.setToolTipText(resourceMap.getString("jButtonCargar.toolTipText")); // NOI18N
        jButtonCargar.setName("jButtonCargar"); // NOI18N
        jButtonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPropiedadesProyecto, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(jButtonCargar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar))
                    .addComponent(jPanelBuscador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancelar, jButtonCargar, jButtonEliminar, jButtonModificar, jButtonSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPropiedadesProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonEliminar)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonCargar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelar
        if (jButtonSalvar.isEnabled()==true)
        {
            jTextFieldIDAutorB.setText("");
            jTextFieldNombreProyectoB.setText("");
            jTextFieldNombreProyecto.setText("");
            jTextFieldNombreAutor.setText("");
            jTextFieldApellidoAutor.setText("");
            jTextFieldIDAutor.setText("");
            jTextPaneDescripcion.setText("");
            jTextFieldPlanta.setText("");
            jTextFieldSubSistema.setText("");
            jTextFieldEquipo.setText("");
            jTextFieldNombreProyecto.setEnabled(false);
            jTextFieldNombreAutor.setEnabled(false);
            jTextFieldApellidoAutor.setEnabled(false);      
            jTextPaneDescripcion.setEnabled(false);
            jTextFieldPlanta.setEnabled(false);
            jTextFieldEquipo.setEnabled(false);
            jTextFieldSubSistema.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonModificar.setEnabled(true);
            jTextFieldIDAutorB.setEnabled(true);
            jButtonBuscar1.setEnabled(true);
            jTextFieldNombreProyectoB.setEnabled(true);
            jButtonBuscar2.setEnabled(true);
            jListProyectos.setEnabled(true);
            jButtonCargar.setEnabled(true);
            jButtonEliminar.setEnabled(true);
            jListProyectos.setModel(new DefaultListModel());
        }
        else
        {
            jTextFieldIDAutorB.setText("");
            jTextFieldNombreProyectoB.setText("");
            jTextFieldNombreProyecto.setText("");
            jTextFieldNombreAutor.setText("");
            jTextFieldApellidoAutor.setText("");
            jTextFieldIDAutor.setText("");
            jTextPaneDescripcion.setText("");
            jTextFieldPlanta.setText("");
            jTextFieldSubSistema.setText("");
            jTextFieldEquipo.setText("");            
            jListProyectos.setModel(new DefaultListModel());
            dispose();
        }
}//GEN-LAST:event_botonCancelar

    private void botonBuscar1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscar1
        try
        {
            if (jTextFieldIDAutorB.getText().equals(""))
                query =  "SELECT*FROM APCON.persona_datos INNER JOIN APCON.proyecto_datos ON " +
                    "persona_datos.Cedula = proyecto_datos.Id_pers ORDER BY Cedula";
            else
                query = "SELECT*FROM APCON.persona_datos INNER JOIN APCON.proyecto_datos ON " +
                    "persona_datos.Cedula = proyecto_datos.Id_pers " +
                    " WHERE Id_pers = '" + jTextFieldIDAutorB.getText() + "'ORDER BY Nombre_proy";
            
            jListProyectos.setModel(gestionar.buscar(query));
        }

        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "Error: "+ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        catch (ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, "Error: "+ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_botonBuscar1

    private void botonBuscar2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscar2
        try
        {
            if (jTextFieldNombreProyectoB.getText().equals(""))
                query = "SELECT*FROM APCON.persona_datos INNER JOIN APCON.proyecto_datos ON " +
                    "persona_datos.Cedula = proyecto_datos.Id_pers ORDER BY Nombre_proy";
            else
                query = "SELECT*FROM APCON.persona_datos INNER JOIN APCON.proyecto_datos ON " +
                    "persona_datos.Cedula = proyecto_datos.Id_pers " +
                    " WHERE Nombre_proy = '" + jTextFieldNombreProyectoB.getText() + "'";
            
            jListProyectos.setModel(gestionar.buscar(query));
        }

        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "Error: "+ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        catch (ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, "Error: "+ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_botonBuscar2

    private void botonModificar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificar
        if (!jTextFieldNombreProyecto.getText().equals(""))
        {
            jTextFieldIDAutorB.setEnabled(false);
            jButtonBuscar1.setEnabled(false);
            jTextFieldNombreProyectoB.setEnabled(false);
            jButtonBuscar2.setEnabled(false);
            jTextFieldNombreProyecto.setEnabled(true);
            jTextFieldNombreAutor.setEnabled(true);
            jTextFieldApellidoAutor.setEnabled(true);
            jTextPaneDescripcion.setEnabled(true);
            jTextFieldPlanta.setEnabled(true);
            jTextFieldSubSistema.setEnabled(true);
            jTextFieldEquipo.setEnabled(true);
            jButtonSalvar.setEnabled(true);
            jButtonModificar.setEnabled(false);
            jButtonCargar.setEnabled(false);
            jButtonEliminar.setEnabled(false);
            jButtonModificar.transferFocus();
        }
        else
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Proyecto");

    }//GEN-LAST:event_botonModificar

    private void botonSalvar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalvar
        person.setApellido(jTextFieldApellidoAutor.getText());
        person.setDescripcion(jTextPaneDescripcion.getText());
        person.setEquipo(jTextFieldEquipo.getText());
        person.setNombre(jTextFieldNombreAutor.getText());
        person.setPlanta(jTextFieldPlanta.getText());
        person.setProyecto(jTextFieldNombreProyecto.getText());
        person.setSubSistema(jTextFieldSubSistema.getText());

        if (gestionar.validarCampo(jTextFieldNombreAutor.getText()) == 0||
                gestionar.validarCampo(jTextFieldNombreProyecto.getText()) == 0 ||
                gestionar.validarCampo(jTextFieldIDAutor.getText()) == 0 ||
                gestionar.validarCampo(jTextFieldPlanta.getText()) == 0 ||
                gestionar.validarCampo(jTextFieldApellidoAutor.getText()) == 0 ||
                gestionar.validarCampo(jTextFieldSubSistema.getText()) == 0 ||
                gestionar.validarCampo(jTextFieldEquipo.getText()) == 0 ||
                gestionar.validarCampo(jTextPaneDescripcion.getText()) == 0)
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
        else
        {
            try 
            {
                gestionar.salvar(person);
                jTextFieldNombreProyecto.setEnabled(false);
                jTextFieldNombreAutor.setEnabled(false);
                jTextFieldApellidoAutor.setEnabled(false);
                jTextPaneDescripcion.setEnabled(false);
                jTextFieldPlanta.setEnabled(false);
                jTextFieldEquipo.setEnabled(false);
                jTextFieldSubSistema.setEnabled(false);
                jButtonSalvar.setEnabled(false);
                jButtonModificar.setEnabled(true);
                jTextFieldIDAutorB.setEnabled(true);
                jButtonBuscar1.setEnabled(true);
                jTextFieldNombreProyectoB.setEnabled(true);
                jButtonBuscar2.setEnabled(true);
                jButtonCargar.setEnabled(true);
                jButtonEliminar.setEnabled(true);
            } 
           
            catch (SQLException ex)
            {
                JOptionPane.showMessageDialog(null, "Error: "+ex, "ERROR", JOptionPane.ERROR_MESSAGE);
            }
           
            try
            {
                jListProyectos.setModel(gestionar.buscar(query));
                jTextFieldIDAutorB.setText("");
                jTextFieldNombreProyectoB.setText("");
                jTextFieldNombreProyecto.setText("");
                jTextFieldNombreAutor.setText("");
                jTextFieldApellidoAutor.setText("");
                jTextFieldIDAutor.setText("");
                jTextPaneDescripcion.setText("");
                jTextFieldPlanta.setText("");
                jTextFieldSubSistema.setText("");
                jTextFieldEquipo.setText("");
            }
            
            catch (SQLException ex)
            {
                JOptionPane.showMessageDialog(null, "Error: "+ex, "ERROR", JOptionPane.ERROR_MESSAGE);
            }

            catch (ClassNotFoundException ex)
            {
                JOptionPane.showMessageDialog(null, "Error: "+ex, "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_botonSalvar

    private void botonEliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminar

        if (!jTextFieldNombreProyecto.getText().equals(""))
        {
            gestionar.eliminar(JOptionPane.showConfirmDialog(null,"¿Desea Eliminar " +
                    "este proyecto?", "Seleccione una Opción", JOptionPane.YES_NO_OPTION,
                    JOptionPane.PLAIN_MESSAGE, null));

            try
            {
                jListProyectos.setModel(gestionar.buscar(query));
            }

            catch (SQLException ex)
            {
                JOptionPane.showMessageDialog(null, "Error: "+ex, "ERROR", JOptionPane.ERROR_MESSAGE);
            }

            catch (ClassNotFoundException ex)
            {
                JOptionPane.showMessageDialog(null, "Error: "+ex, "ERROR", JOptionPane.ERROR_MESSAGE);
            }

            finally
            {
                jTextFieldNombreProyecto.setText("");
                jTextFieldNombreAutor.setText("");
                jTextFieldApellidoAutor.setText("");
                jTextFieldIDAutor.setText("");
                jTextPaneDescripcion.setText("");
                jTextFieldPlanta.setText("");
                jTextFieldSubSistema.setText("");
                jTextFieldEquipo.setText("");
                jTextFieldIDAutorB.setText("");
                jTextFieldNombreProyectoB.setText("");
                jCheckBoxWeibull.setSelected(false);
                jCheckBoxSFR.setSelected(false);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Primero debe seleccionar " +
                    "un proyecto.", "ERROR", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_botonEliminar

    private void botonCargar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargar

        if (!jTextFieldNombreProyecto.getText().equals(""))
        {
            gestionar.cargar();

            JOptionPane.showMessageDialog(null, "El proyecto \"" +
                        jTextFieldNombreProyecto.getText() +  "\" ha sido cargado.",
                        "Información", JOptionPane.INFORMATION_MESSAGE);

            jTextFieldIDAutorB.setText("");
            jTextFieldNombreProyectoB.setText("");
            jTextFieldNombreProyecto.setText("");
            jTextFieldNombreAutor.setText("");
            jTextFieldApellidoAutor.setText("");
            jTextFieldIDAutor.setText("");
            jTextPaneDescripcion.setText("");
            jTextFieldPlanta.setText("");
            jTextFieldSubSistema.setText("");
            jTextFieldEquipo.setText("");
            jListProyectos.setModel(new DefaultListModel());

            dispose();
        }
        else
            JOptionPane.showMessageDialog(null, "Primero debe seleccionar " +
                    "un proyecto.", "ERROR", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_botonCargar

    private void listaProyectos(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaProyectos
        if (jButtonSalvar.isEnabled()==false)
        {
            if (jListProyectos.isEnabled()==false)
                JOptionPane.showMessageDialog(null, "No se pueede cambiar de proyecto " +
                        "durante la modificación.", "Error", JOptionPane.WARNING_MESSAGE, null);

            person = gestionar.seleccionarProyecto(jListProyectos.getSelectedIndex());

            jTextFieldNombreProyecto.setText(person.getProyecto());
            jTextFieldNombreAutor.setText(person.getNombre());
            jTextFieldApellidoAutor.setText(person.getApellido());
            jTextFieldIDAutor.setText(person.getCedula());
            jTextPaneDescripcion.setText(person.getDescripcion());
            jTextFieldPlanta.setText(person.getPlanta());
            jTextFieldSubSistema.setText(person.getSubSistema());
            jTextFieldEquipo.setText(person.getEquipo());
            jCheckBoxSFR.setSelected(person.getSFR());
            jCheckBoxWeibull.setSelected(person.getWeibull());
        }
    }//GEN-LAST:event_listaProyectos

    private void jTextFieldIDAutorBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDAutorBKeyTyped
        gestionar.validacionCampo(evt,"[0-9]");
        char caracter = evt.getKeyChar();
        if (caracter == KeyEvent.VK_SPACE) evt.consume();
        gestionar.validarTamaño(jTextFieldIDAutorB.getText(), 8, evt);
    }//GEN-LAST:event_jTextFieldIDAutorBKeyTyped

    private void jTextFieldNombreProyectoBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreProyectoBKeyTyped
        gestionar.validacionCampo(evt,"[-0-9á-úÁ-Úa-zA-Z]");
        gestionar.validarTamaño(jTextFieldNombreProyectoB.getText(),30,evt);
    }//GEN-LAST:event_jTextFieldNombreProyectoBKeyTyped

    private void jTextFieldIDAutorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDAutorBActionPerformed
        jTextFieldIDAutorB.transferFocus();
    }//GEN-LAST:event_jTextFieldIDAutorBActionPerformed

    private void jTextFieldNombreProyectoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreProyectoBActionPerformed
        jTextFieldNombreProyectoB.transferFocus();
    }//GEN-LAST:event_jTextFieldNombreProyectoBActionPerformed

    private void jTextPaneDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPaneDescripcionKeyTyped
        gestionar.validacionCampo(evt, "[,-.:-;0-9á-úÁ-Úa-zA-Z(-)]");
        char enter = evt.getKeyChar();
        if (enter == KeyEvent.VK_ENTER) jButtonModificar.transferFocus();
        gestionar.validarTamaño(jTextPaneDescripcion.getText(), 255, evt);
    }//GEN-LAST:event_jTextPaneDescripcionKeyTyped

    private void jTextFieldNombreProyectoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreProyectoKeyTyped
        gestionar.validacionCampo(evt, "[-0-9á-úÁ-Úa-zA-Z]");
        gestionar.validarTamaño(jTextFieldNombreProyecto.getText(), 30, evt);
    }//GEN-LAST:event_jTextFieldNombreProyectoKeyTyped

    private void jTextFieldNombreProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreProyectoActionPerformed
        jTextFieldNombreProyecto.transferFocus();
    }//GEN-LAST:event_jTextFieldNombreProyectoActionPerformed

    private void jTextFieldNombreAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreAutorKeyTyped
        gestionar.validacionCampo(evt, "[á-úÁ-Úa-zA-Z]");
        gestionar.validarTamaño(jTextFieldNombreAutor.getText(), 10, evt);
    }//GEN-LAST:event_jTextFieldNombreAutorKeyTyped

    private void jTextFieldNombreAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreAutorActionPerformed
        jTextFieldNombreAutor.transferFocus();
    }//GEN-LAST:event_jTextFieldNombreAutorActionPerformed

    private void jTextFieldApellidoAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidoAutorKeyTyped
        gestionar.validacionCampo(evt, "[á-úÁ-Úa-zA-Z]");
        gestionar.validarTamaño(jTextFieldApellidoAutor.getText(), 15, evt);
    }//GEN-LAST:event_jTextFieldApellidoAutorKeyTyped

    private void jTextFieldApellidoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoAutorActionPerformed
        jTextFieldApellidoAutor.transferFocus();
    }//GEN-LAST:event_jTextFieldApellidoAutorActionPerformed

    private void jTextFieldIDAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDAutorKeyTyped
        gestionar.validacionCampo(evt, "[0-9]");
        char caracter = evt.getKeyChar();
        if (caracter == KeyEvent.VK_SPACE) evt.consume();
    }//GEN-LAST:event_jTextFieldIDAutorKeyTyped

    private void jTextFieldIDAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDAutorActionPerformed
        jTextFieldIDAutor.transferFocus();
    }//GEN-LAST:event_jTextFieldIDAutorActionPerformed

    private void jTextFieldPlantaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPlantaKeyTyped
        gestionar.validacionCampo(evt, "[-0-9á-úÁ-Úa-zA-Z]");
        gestionar.validarTamaño(jTextFieldPlanta.getText(), 15, evt);
    }//GEN-LAST:event_jTextFieldPlantaKeyTyped

    private void jTextFieldPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlantaActionPerformed
        jTextFieldPlanta.transferFocus();
    }//GEN-LAST:event_jTextFieldPlantaActionPerformed

    private void jTextFieldSubSistemaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSubSistemaKeyTyped
        gestionar.validacionCampo(evt, "[-0-9á-úÁ-Úa-zA-Z]");
        gestionar.validarTamaño(jTextFieldSubSistema.getText(), 15, evt);
    }//GEN-LAST:event_jTextFieldSubSistemaKeyTyped

    private void jTextFieldSubSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSubSistemaActionPerformed
        jTextFieldSubSistema.transferFocus();
    }//GEN-LAST:event_jTextFieldSubSistemaActionPerformed

    private void jTextFieldEquipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEquipoKeyTyped
        gestionar.validacionCampo(evt, "[-0-9á-úÁ-Úa-zA-Z]");
        gestionar.validarTamaño(jTextFieldEquipo.getText(), 15, evt);
    }//GEN-LAST:event_jTextFieldEquipoKeyTyped

    private void jTextFieldEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEquipoActionPerformed
        jTextFieldEquipo.transferFocus();
    }//GEN-LAST:event_jTextFieldEquipoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar1;
    private javax.swing.JButton jButtonBuscar2;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JCheckBox jCheckBoxSFR;
    private javax.swing.JCheckBox jCheckBoxWeibull;
    private javax.swing.JLabel jLabelApellidoAutor;
    private javax.swing.JLabel jLabelEquipo;
    private javax.swing.JLabel jLabelIDAutor;
    private javax.swing.JLabel jLabelIDAutorB;
    private javax.swing.JLabel jLabelNombreAutor;
    private javax.swing.JLabel jLabelNombreProyecto;
    private javax.swing.JLabel jLabelNombreProyectoB;
    private javax.swing.JLabel jLabelPlanta;
    private javax.swing.JLabel jLabelSubSistema;
    private javax.swing.JList jListProyectos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBuscador;
    private javax.swing.JPanel jPanelDescripcion;
    private javax.swing.JPanel jPanelPropiedadesProyecto;
    private javax.swing.JPanel jPanelProyectos;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldApellidoAutor;
    private javax.swing.JTextField jTextFieldEquipo;
    private javax.swing.JTextField jTextFieldIDAutor;
    private javax.swing.JTextField jTextFieldIDAutorB;
    private javax.swing.JTextField jTextFieldNombreAutor;
    private javax.swing.JTextField jTextFieldNombreProyecto;
    private javax.swing.JTextField jTextFieldNombreProyectoB;
    private javax.swing.JTextField jTextFieldPlanta;
    private javax.swing.JTextField jTextFieldSubSistema;
    private javax.swing.JTextPane jTextPaneDescripcion;
    // End of variables declaration//GEN-END:variables
}