package apcon;

import java.sql.SQLException;
import java.util.List;
import java.io.*;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IUGenerarGraficaSFR.java
 *
 * Created on 07/05/2010, 10:15:11 AM
 */

/**
 * @author Andres
 */
public class IUGenerarGraficaSFR extends javax.swing.JFrame {
    private DefaultTableModel model;
    private GestorGenerarGraficaSFR graficaSFR;
    private SFRDatos sfr;
    private Proyecto proy = new Proyecto();
    private List<SFRDatos> results;
    private List<Proyecto> results1;
    private ImageIcon grafica;
    protected final NumberFormat numberFormatterObj = NumberFormat.getInstance();

    /** Creates new form IUGenerarGraficaSFR */
    public IUGenerarGraficaSFR() throws SQLException, ClassNotFoundException, FileNotFoundException {
        NumberFormat F = numberFormatterObj;
        graficaSFR = new GestorGenerarGraficaSFR();
        setupNumberFmtObj(4);
        sfr = new SFRDatos();
        results1 = graficaSFR.getProyecto(graficaSFR.getProyectoCargado());
        proy = results1.get(0);
        results = graficaSFR.getSFRDatos(graficaSFR.getProyectoCargado());

        model = new DefaultTableModel()
        { 
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return false;
            }
        };

        model.addColumn("i");
        model.addColumn("d(i)");
        model.addColumn("c(i)");
        model.addColumn("c/2(i)");
        model.addColumn("n'(i)");
        model.addColumn("n(i)");
        model.addColumn("q(i)");
        model.addColumn("p(i)");
        model.addColumn("S(i)");
        model.addColumn("f(mi)");
        model.addColumn("P(mi)");
        model.addColumn("h(i)");
        model.addColumn("F(i)");
        model.addColumn("S(i)+F(i)");

        for (int i=0; i<results.size();i++)
        {
            sfr = results.get(i);

            model.addRow(new Object[] {
                sfr.getIntervalo(),
                sfr.getFallas(),
                sfr.getDC(),
                sfr.getDC2(),
                sfr.getObs(),
                sfr.getObsR(),
                F.format(sfr.getQ()).replace(",", "."),
                F.format(sfr.getP()).replace(",", "."),
                F.format(sfr.getSi()).replace(",", "."),
                F.format(sfr.getFmi()).replace(",", "."),
                F.format(sfr.getPmi()).replace(",", "."),
                F.format(sfr.getHi()).replace(",", "."),
                F.format(sfr.getFi()).replace(",", "."),
                sfr.getSiFi()});
        }

        initComponents();
        jLabelGrafica.setIcon(null);
        grafica = new ImageIcon();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jButtonProcesar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelGrafica = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSFR = new javax.swing.JTable(model);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(proy.getProyecto());
        setName("Form2"); // NOI18N
        setResizable(false);

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(apcon.APCONApp.class).getContext().getResourceMap(IUGenerarGraficaSFR.class);
        jButtonSalir.setFont(resourceMap.getFont("jButtonProcesar.font")); // NOI18N
        jButtonSalir.setText(resourceMap.getString("jButtonSalir.text")); // NOI18N
        jButtonSalir.setToolTipText(resourceMap.getString("jButtonSalir.toolTipText")); // NOI18N
        jButtonSalir.setName("jButtonSalir"); // NOI18N
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalir(evt);
            }
        });

        jButtonProcesar.setFont(resourceMap.getFont("jButtonProcesar.font")); // NOI18N
        jButtonProcesar.setText(resourceMap.getString("jButtonProcesar.text")); // NOI18N
        jButtonProcesar.setToolTipText(resourceMap.getString("jButtonProcesar.toolTipText")); // NOI18N
        jButtonProcesar.setName("jButtonProcesar"); // NOI18N
        jButtonProcesar.setNextFocusableComponent(jButtonSalir);
        jButtonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProcesar(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel2.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel2.border.titleFont"), resourceMap.getColor("jPanel2.border.titleColor"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jLabelGrafica.setFont(resourceMap.getFont("jLabelGrafica.font")); // NOI18N
        jLabelGrafica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGrafica.setText(resourceMap.getString("jLabelGrafica.text")); // NOI18N
        jLabelGrafica.setToolTipText(resourceMap.getString("jLabelGrafica.toolTipText")); // NOI18N
        jLabelGrafica.setName("jLabelGrafica"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel3.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel3.border.titleFont"), resourceMap.getColor("jPanel3.border.titleColor"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTableSFR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableSFR.setFont(resourceMap.getFont("jTableSFR.font")); // NOI18N
        jTableSFR.setToolTipText(resourceMap.getString("jTableSFR.toolTipText")); // NOI18N
        jTableSFR.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableSFR.setName("jTableSFR"); // NOI18N
        jTableSFR.setRequestFocusEnabled(false);
        jTableSFR.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableSFR.getTableHeader().setReorderingAllowed(false);
        jTableSFR.setUpdateSelectionOnSort(false);
        jTableSFR.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(jTableSFR);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(645, Short.MAX_VALUE)
                .addComponent(jButtonProcesar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalir)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonProcesar, jButtonSalir});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalir)
                    .addComponent(jButtonProcesar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonProcesar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProcesar
        graficaSFR.procesarDatos(results, proy, "SFR");
        grafica = null;
        grafica = new ImageIcon("C:/APCON/Recursos/SFRTemp.jpg");
        jLabelGrafica.setIcon(grafica);
        jButtonProcesar.setEnabled(false);
        jButtonProcesar.transferFocus();
}//GEN-LAST:event_botonProcesar

    private void botonSalir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalir
        jButtonProcesar.setEnabled(true);
        jLabelGrafica.setIcon(null);
        grafica = new ImageIcon();
        dispose();
}//GEN-LAST:event_botonSalir

    protected void setupNumberFmtObj(int k)
    {
        String patron = "0.";
        for (int j=0; j<k; j++)
            patron = patron + "#";
        if (this.numberFormatterObj instanceof DecimalFormat) {
            ((DecimalFormat) this.numberFormatterObj).applyPattern(patron);
        }
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonProcesar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelGrafica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSFR;
    // End of variables declaration//GEN-END:variables

}
