/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * APCONWeibull.java
 *
 * Created on 09/06/2010, 03:59:49 PM
 */

package apcon;

import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import java.text.NumberFormat;

/**
 *
 * @author Andres
 */
public class IURealizarDistWeibull extends javax.swing.JFrame {

    int row = 0;
    int x,y;
    int control1 = 0;
    int nIntervalos;
    double [] fallac_w;
    GestorRealizarDistWeibull gestor;
    private DatosWeibull datosWeibull;
    private Parametros param;
    private List<DatosWeibull> results;
    private List<Parametros> results1;
    private List<Proyecto> results2;
    private DefaultTableModel model;
    private Proyecto proy = new Proyecto();
    protected final NumberFormat numberFormatterObj = NumberFormat.getInstance();
    
    public IURealizarDistWeibull() throws SQLException, ClassNotFoundException, FileNotFoundException {
        gestor = new GestorRealizarDistWeibull();
        setupNumberFmtObj(4);
        int i =0;
        NumberFormat F = numberFormatterObj;

        model = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return false;
            }
        };

        results2 = gestor.getProyecto(gestor.getProyectoCargado());
        proy = results2.get(0);
        results = gestor.getDatosWeibull(gestor.getProyectoCargado());
        x = results.size();

        if(results.size()==0)
        {
            model.addColumn("Intervalo");
            model.addColumn("T.E.F");
            model.addColumn("Fi");
            model.addColumn("Fi[%]");

            initComponents();
        }
        else
        {
            model.addColumn("Intervalo");
            model.addColumn("T.E.F");
            model.addColumn("Fi");
            model.addColumn("Fi[%]");

            while (i<results.size())
            {
                datosWeibull = results.get(i);

                model.addRow(new Object[] {
                    datosWeibull.getIntervalo(),
                    datosWeibull.getTEF(),
                    F.format(datosWeibull.getFallaAc()).replace(",", "."),
                    F.format(datosWeibull.getFallaAc()*100).replace(",", ".")});

                i++;
            }

            initComponents();
            jTextFieldNIntervalos.setText(Integer.toString(results.size()));
            jTextFieldNIntervalos.setEditable(false);
            jTextFieldIntervalo.setText(Integer.toString(i+1));
            jButtonModificar.setEnabled(true);
            jButtonModificarI.setEnabled(true);
            jButtonCargar.setEnabled(false);
            jButtonProcesar.setEnabled(false);
            jButtonSiguiente.setEnabled(true);
            jButtonEstimar.setEnabled(false);
         }

        results1 = gestor.getParametros(gestor.getProyectoCargado());
        y = results1.size();

        if (y>0)
        {
            param = results1.get(0);
            jTextFieldBeta.setText(Double.toString(param.getForma()));
            jTextFieldEscala.setText(Double.toString(param.getEscala()));
            jTextFieldPosicion.setText(Double.toString(param.getPosicion()));

            if (param.getPosicion()!=0)
            {

                model.addColumn("T.E.F.-γ");
                jTableWeibull.setModel(model);
                for (int k=0; k<jTableWeibull.getRowCount();k++)
                    jTableWeibull.setValueAt(Double.parseDouble(F.format((Double)
                            jTableWeibull.getValueAt(k, 1)-param.getPosicion()).replace(",", ".")), k, 4);
            }

            jTextFieldEscala.setEditable(false);
            jTextFieldBeta.setEditable(false);
            jTextFieldPosicion.setEditable(false);
            jButtonCargarP.setEnabled(false);
            jButtonCalcular.setEnabled(false);
            jTextFieldT1.setEditable(false);
            jTextFieldT2.setEditable(false);
            jTextFieldT3.setEditable(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldNIntervalos = new javax.swing.JTextField();
        jLabelNDias = new javax.swing.JLabel();
        jButtonCargar = new javax.swing.JButton();
        jButtonModificarI = new javax.swing.JButton();
        jButtonCancelarI = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldIntervalo = new javax.swing.JTextField();
        jTextFieldTEF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableWeibull = new javax.swing.JTable(model);
        jButtonInsertar = new javax.swing.JButton();
        jLabelNFallas = new javax.swing.JLabel();
        jLabelIntervalo = new javax.swing.JLabel();
        jButtonProcesar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonSiguiente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelBeta = new javax.swing.JLabel();
        jTextFieldBeta = new javax.swing.JTextField();
        jLabelEscala = new javax.swing.JLabel();
        jTextFieldEscala = new javax.swing.JTextField();
        jLabelPosicion = new javax.swing.JLabel();
        jTextFieldPosicion = new javax.swing.JTextField();
        jButtonCargarP = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelT1 = new javax.swing.JLabel();
        jTextFieldT1 = new javax.swing.JTextField();
        jLabelT2 = new javax.swing.JLabel();
        jTextFieldT2 = new javax.swing.JTextField();
        jLabelT3 = new javax.swing.JLabel();
        jTextFieldT3 = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jButtonEstimar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(proy.getProyecto());
        setName("Form3"); // NOI18N
        setResizable(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(apcon.APCONApp.class).getContext().getResourceMap(IURealizarDistWeibull.class);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel2.border.titleFont"), resourceMap.getColor("jPanel2.border.titleColor"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jTextFieldNIntervalos.setFont(resourceMap.getFont("jTextFieldNIntervalos.font")); // NOI18N
        jTextFieldNIntervalos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNIntervalos.setName("jTextFieldNIntervalos"); // NOI18N
        jTextFieldNIntervalos.setNextFocusableComponent(jButtonCargar);
        jTextFieldNIntervalos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNIntervalosActionPerformed(evt);
            }
        });
        jTextFieldNIntervalos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNIntervalosKeyTyped(evt);
            }
        });

        jLabelNDias.setFont(resourceMap.getFont("jLabelNDias.font")); // NOI18N
        jLabelNDias.setText(resourceMap.getString("jLabelNDias.text")); // NOI18N
        jLabelNDias.setName("jLabelNDias"); // NOI18N

        jButtonCargar.setFont(resourceMap.getFont("jButtonCargar.font")); // NOI18N
        jButtonCargar.setText(resourceMap.getString("jButtonCargar.text")); // NOI18N
        jButtonCargar.setAlignmentX(0.5F);
        jButtonCargar.setName("jButtonCargar"); // NOI18N
        jButtonCargar.setNextFocusableComponent(jTextFieldTEF);
        jButtonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargar(evt);
            }
        });

        jButtonModificarI.setFont(resourceMap.getFont("jButtonModificarI.font")); // NOI18N
        jButtonModificarI.setText(resourceMap.getString("jButtonModificarI.text")); // NOI18N
        jButtonModificarI.setEnabled(false);
        jButtonModificarI.setName("jButtonModificarI"); // NOI18N
        jButtonModificarI.setNextFocusableComponent(jTextFieldNIntervalos);
        jButtonModificarI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarI(evt);
            }
        });

        jButtonCancelarI.setFont(resourceMap.getFont("jButtonCancelarI.font")); // NOI18N
        jButtonCancelarI.setText(resourceMap.getString("jButtonCancelarI.text")); // NOI18N
        jButtonCancelarI.setEnabled(false);
        jButtonCancelarI.setName("jButtonCancelarI"); // NOI18N
        jButtonCancelarI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarI(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNDias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNIntervalos, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModificarI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelarI)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNIntervalos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNDias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificarI)
                    .addComponent(jButtonCancelarI)
                    .addComponent(jButtonCargar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel2.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel2.border.titleFont"), resourceMap.getColor("jPanel2.border.titleColor"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jTextFieldIntervalo.setEditable(false);
        jTextFieldIntervalo.setFont(resourceMap.getFont("jTextFieldIntervalo.font")); // NOI18N
        jTextFieldIntervalo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIntervalo.setText(resourceMap.getString("jTextFieldIntervalo.text")); // NOI18N
        jTextFieldIntervalo.setName("jTextFieldIntervalo"); // NOI18N

        jTextFieldTEF.setFont(resourceMap.getFont("jTextFieldTEF.font")); // NOI18N
        jTextFieldTEF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTEF.setEnabled(false);
        jTextFieldTEF.setName("jTextFieldTEF"); // NOI18N
        jTextFieldTEF.setNextFocusableComponent(jButtonInsertar);
        jTextFieldTEF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTEFActionPerformed(evt);
            }
        });
        jTextFieldTEF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTEFKeyTyped(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTableWeibull.setFont(resourceMap.getFont("jTableWeibull.font")); // NOI18N
        jTableWeibull.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableWeibull.setName("jTableWeibull"); // NOI18N
        jTableWeibull.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableWeibull.setSurrendersFocusOnKeystroke(true);
        jTableWeibull.getTableHeader().setReorderingAllowed(false);
        jTableWeibull.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableWeibullMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTableWeibull);

        jButtonInsertar.setFont(resourceMap.getFont("jButtonInsertar.font")); // NOI18N
        jButtonInsertar.setText(resourceMap.getString("jButtonInsertar.text")); // NOI18N
        jButtonInsertar.setToolTipText(resourceMap.getString("jButtonInsertar.toolTipText")); // NOI18N
        jButtonInsertar.setEnabled(false);
        jButtonInsertar.setName("jButtonInsertar"); // NOI18N
        jButtonInsertar.setNextFocusableComponent(jTextFieldTEF);
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertar(evt);
            }
        });

        jLabelNFallas.setFont(resourceMap.getFont("jLabelNFallas.font")); // NOI18N
        jLabelNFallas.setText(resourceMap.getString("jLabelNFallas.text")); // NOI18N
        jLabelNFallas.setName("jLabelNFallas"); // NOI18N

        jLabelIntervalo.setFont(resourceMap.getFont("jLabelIntervalo.font")); // NOI18N
        jLabelIntervalo.setText(resourceMap.getString("jLabelIntervalo.text")); // NOI18N
        jLabelIntervalo.setName("jLabelIntervalo"); // NOI18N

        jButtonProcesar.setFont(resourceMap.getFont("jButtonProcesar.font")); // NOI18N
        jButtonProcesar.setText(resourceMap.getString("jButtonProcesar.text")); // NOI18N
        jButtonProcesar.setEnabled(false);
        jButtonProcesar.setName("jButtonProcesar"); // NOI18N
        jButtonProcesar.setNextFocusableComponent(jButtonEstimar);
        jButtonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProcesar(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelIntervalo)
                            .addComponent(jLabelNFallas))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIntervalo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTEF, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButtonInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonProcesar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11)))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonInsertar, jButtonProcesar});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldIntervalo, jTextFieldTEF});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelIntervalo)
                                .addComponent(jTextFieldIntervalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldTEF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNFallas))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonInsertar)
                            .addComponent(jButtonProcesar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonModificar.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jButtonModificar.setText(resourceMap.getString("jButtonModificar.text")); // NOI18N
        jButtonModificar.setEnabled(false);
        jButtonModificar.setName("jButtonModificar"); // NOI18N
        jButtonModificar.setNextFocusableComponent(jTextFieldTEF);
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificar(evt);
            }
        });

        jButtonSalvar.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jButtonSalvar.setText(resourceMap.getString("jButtonSalvar.text")); // NOI18N
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.setName("jButtonSalvar"); // NOI18N
        jButtonSalvar.setNextFocusableComponent(jButtonProcesar);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalvar(evt);
            }
        });

        jButtonSalir.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jButtonSalir.setText(resourceMap.getString("jButtonSalir.text")); // NOI18N
        jButtonSalir.setToolTipText(resourceMap.getString("jButtonSalir.toolTipText")); // NOI18N
        jButtonSalir.setName("jButtonSalir"); // NOI18N
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalir(evt);
            }
        });

        jButtonSiguiente.setFont(resourceMap.getFont("jButtonSalvar.font")); // NOI18N
        jButtonSiguiente.setText(resourceMap.getString("jButtonSiguiente.text")); // NOI18N
        jButtonSiguiente.setEnabled(false);
        jButtonSiguiente.setName("jButtonSiguiente"); // NOI18N
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguiente(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel3.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel3.border.titleFont"), resourceMap.getColor("jPanel3.border.titleColor"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        jLabelBeta.setFont(resourceMap.getFont("jLabelBeta.font")); // NOI18N
        jLabelBeta.setText(resourceMap.getString("jLabelBeta.text")); // NOI18N
        jLabelBeta.setName("jLabelBeta"); // NOI18N

        jTextFieldBeta.setFont(resourceMap.getFont("jTextFieldBeta.font")); // NOI18N
        jTextFieldBeta.setText(resourceMap.getString("jTextFieldBeta.text")); // NOI18N
        jTextFieldBeta.setName("jTextFieldBeta"); // NOI18N
        jTextFieldBeta.setNextFocusableComponent(jTextFieldEscala);
        jTextFieldBeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBetaActionPerformed(evt);
            }
        });
        jTextFieldBeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBetaKeyTyped(evt);
            }
        });

        jLabelEscala.setFont(resourceMap.getFont("jLabelEscala.font")); // NOI18N
        jLabelEscala.setText(resourceMap.getString("jLabelEscala.text")); // NOI18N
        jLabelEscala.setName("jLabelEscala"); // NOI18N

        jTextFieldEscala.setFont(resourceMap.getFont("jTextField1.font")); // NOI18N
        jTextFieldEscala.setText(resourceMap.getString("jTextFieldEscala.text")); // NOI18N
        jTextFieldEscala.setName("jTextFieldEscala"); // NOI18N
        jTextFieldEscala.setNextFocusableComponent(jTextFieldPosicion);
        jTextFieldEscala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEscalaActionPerformed(evt);
            }
        });
        jTextFieldEscala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEscalaKeyTyped(evt);
            }
        });

        jLabelPosicion.setFont(resourceMap.getFont("jLabelPosicion.font")); // NOI18N
        jLabelPosicion.setText(resourceMap.getString("jLabelPosicion.text")); // NOI18N
        jLabelPosicion.setName("jLabelPosicion"); // NOI18N

        jTextFieldPosicion.setFont(resourceMap.getFont("jTextField1.font")); // NOI18N
        jTextFieldPosicion.setText(resourceMap.getString("jTextFieldPosicion.text")); // NOI18N
        jTextFieldPosicion.setName("jTextFieldPosicion"); // NOI18N
        jTextFieldPosicion.setNextFocusableComponent(jButtonCargarP);
        jTextFieldPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPosicionActionPerformed(evt);
            }
        });
        jTextFieldPosicion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPosicionKeyTyped(evt);
            }
        });

        jButtonCargarP.setFont(resourceMap.getFont("jTextField1.font")); // NOI18N
        jButtonCargarP.setText(resourceMap.getString("jButtonCargarP.text")); // NOI18N
        jButtonCargarP.setName("jButtonCargarP"); // NOI18N
        jButtonCargarP.setNextFocusableComponent(jButtonSiguiente);
        jButtonCargarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarP(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEscala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPosicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButtonCargarP, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldBeta, jTextFieldEscala, jTextFieldPosicion});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBeta)
                    .addComponent(jTextFieldBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEscala)
                    .addComponent(jTextFieldEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPosicion)
                    .addComponent(jTextFieldPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCargarP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel4.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel4.border.titleFont"), resourceMap.getColor("jPanel4.border.titleColor"))); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N

        jLabelT1.setFont(resourceMap.getFont("jLabelT1.font")); // NOI18N
        jLabelT1.setText(resourceMap.getString("jLabelT1.text")); // NOI18N
        jLabelT1.setName("jLabelT1"); // NOI18N

        jTextFieldT1.setFont(resourceMap.getFont("jTextFieldT3.font")); // NOI18N
        jTextFieldT1.setText(resourceMap.getString("jTextFieldT1.text")); // NOI18N
        jTextFieldT1.setName("jTextFieldT1"); // NOI18N
        jTextFieldT1.setNextFocusableComponent(jTextFieldT2);
        jTextFieldT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldT1ActionPerformed(evt);
            }
        });
        jTextFieldT1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldT1KeyTyped(evt);
            }
        });

        jLabelT2.setFont(resourceMap.getFont("jLabelT2.font")); // NOI18N
        jLabelT2.setText(resourceMap.getString("jLabelT2.text")); // NOI18N
        jLabelT2.setName("jLabelT2"); // NOI18N

        jTextFieldT2.setFont(resourceMap.getFont("jTextFieldT3.font")); // NOI18N
        jTextFieldT2.setText(resourceMap.getString("jTextFieldT2.text")); // NOI18N
        jTextFieldT2.setName("jTextFieldT2"); // NOI18N
        jTextFieldT2.setNextFocusableComponent(jTextFieldT3);
        jTextFieldT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldT2ActionPerformed(evt);
            }
        });
        jTextFieldT2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldT2KeyTyped(evt);
            }
        });

        jLabelT3.setFont(resourceMap.getFont("jLabelT3.font")); // NOI18N
        jLabelT3.setText(resourceMap.getString("jLabelT3.text")); // NOI18N
        jLabelT3.setName("jLabelT3"); // NOI18N

        jTextFieldT3.setFont(resourceMap.getFont("jTextFieldT3.font")); // NOI18N
        jTextFieldT3.setText(resourceMap.getString("jTextFieldT3.text")); // NOI18N
        jTextFieldT3.setName("jTextFieldT3"); // NOI18N
        jTextFieldT3.setNextFocusableComponent(jButtonCalcular);
        jTextFieldT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldT3ActionPerformed(evt);
            }
        });
        jTextFieldT3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldT3KeyTyped(evt);
            }
        });

        jButtonCalcular.setFont(resourceMap.getFont("jButtonCalcular.font")); // NOI18N
        jButtonCalcular.setText(resourceMap.getString("jButtonCalcular.text")); // NOI18N
        jButtonCalcular.setName("jButtonCalcular"); // NOI18N
        jButtonCalcular.setNextFocusableComponent(jButtonCargarP);
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcular(evt);
            }
        });

        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jButtonEstimar.setFont(resourceMap.getFont("jButtonEstimar.font")); // NOI18N
        jButtonEstimar.setText(resourceMap.getString("jButtonEstimar.text")); // NOI18N
        jButtonEstimar.setName("jButtonEstimar"); // NOI18N
        jButtonEstimar.setNextFocusableComponent(jTextFieldT1);
        jButtonEstimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEstimar(evt);
            }
        });

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelT1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldT1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelT2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldT2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelT3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(jButtonEstimar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldT1, jTextFieldT2, jTextFieldT3});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEstimar)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCalcular)
                    .addComponent(jLabelT1)
                    .addComponent(jTextFieldT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelT2)
                    .addComponent(jTextFieldT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelT3)
                    .addComponent(jTextFieldT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(jButtonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSiguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalir))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonModificar, jButtonSalir, jButtonSalvar, jButtonSiguiente});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalir)
                    .addComponent(jButtonSiguiente)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonModificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonSalir, jButtonSiguiente});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNIntervalosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNIntervalosActionPerformed
        jTextFieldNIntervalos.transferFocus();
    }//GEN-LAST:event_jTextFieldNIntervalosActionPerformed

    private void jTextFieldNIntervalosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNIntervalosKeyTyped
        gestor.validacionCampoChar(evt, "[0-9]");
        gestor.validarTamaño(jTextFieldNIntervalos.getText(), 6, evt);
    }//GEN-LAST:event_jTextFieldNIntervalosKeyTyped

    private void botonCargar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargar
        try
        {
            nIntervalos = Integer.parseInt(jTextFieldNIntervalos.getText());
            
            if (x == 0) {
                for (int i = 0; i<nIntervalos ; i++) model.addRow(new Object [] {});
                jTextFieldNIntervalos.setEditable(false);
                jButtonCargar.setEnabled(false);
                jButtonInsertar.setEnabled(true);
                jTextFieldTEF.setEnabled(true);
                jButtonModificar.setEnabled(true);
                jButtonCancelarI.setEnabled(false);
                jButtonModificarI.setEnabled(true);
                jTextFieldIntervalo.transferFocus();
                x=nIntervalos;
            } 
            else if (nIntervalos>x)
            {
                for (int i = 0; i<model.getRowCount();i++)model.setValueAt(null, i, 2);
                for (int i = 0; i<nIntervalos-x; i++) model.addRow(new Object [] {});
                jTextFieldNIntervalos.setEditable(false);
                jButtonCargar.setEnabled(false);
                jButtonInsertar.setEnabled(true);
                jTextFieldTEF.setEnabled(true);
                jButtonModificar.setEnabled(true);
                jButtonCancelarI.setEnabled(false);
                jButtonModificarI.setEnabled(true);
                jTextFieldIntervalo.transferFocus();
                x=nIntervalos;
            } 
            else
            {
                int i;
                for (i = x; i>nIntervalos; i--) model.removeRow(i-1);
                for (int j = 0; j<model.getRowCount();j++)model.setValueAt(null, j, 2);
                jTextFieldIntervalo.setText(Integer.toString(i+1));
                jTextFieldNIntervalos.setEditable(false);
                jButtonCargar.setEnabled(false);
                jButtonModificar.setEnabled(true);
                jButtonCancelarI.setEnabled(false);
                jButtonModificarI.setEnabled(true);
                jTextFieldTEF.setEnabled(false);
                jButtonInsertar.setEnabled(false);
                x=nIntervalos;
            }

            jButtonCargar.transferFocus();
        }
        
        catch ( NumberFormatException e )
        {
            jTextFieldNIntervalos.setText("");
            
            JOptionPane.showMessageDialog(null, "Debe insertar un valor.");
            
            jButtonSalir.transferFocus();
        }
}//GEN-LAST:event_botonCargar

    private void botonModificarI(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarI
        jButtonModificarI.setEnabled(false);
        jButtonCancelarI.setEnabled(true);        
        jTextFieldNIntervalos.setEditable(true);
        nIntervalos = Integer.parseInt(jTextFieldNIntervalos.getText());
        jButtonCargar.setEnabled(true);
    }//GEN-LAST:event_botonModificarI

    private void botonCancelarI(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarI
        jTextFieldNIntervalos.setText(Integer.toString(nIntervalos));
        jTextFieldNIntervalos.setEditable(false);
        jButtonCancelarI.setEnabled(false);
        jButtonModificarI.setEnabled(true);
        jButtonCargar.setEnabled(false);
}//GEN-LAST:event_botonCancelarI

    private void jTextFieldTEFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTEFActionPerformed
       jTextFieldTEF.transferFocus();
    }//GEN-LAST:event_jTextFieldTEFActionPerformed

    private void jTextFieldTEFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTEFKeyTyped
        gestor.validacionCampoChar(evt, "[.0-9]");
        gestor.validarTamaño(jTextFieldTEF.getText(), 8, evt);
    }//GEN-LAST:event_jTextFieldTEFKeyTyped

    private void jTableWeibullMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableWeibullMouseReleased
        if (jButtonSalvar.isEnabled()==true)
        {
            int y0 = 0;
            row = jTableWeibull.getSelectedRow();

            if (model.getValueAt(row, 0)!=null)
                y0 = ((Integer) model.getValueAt(row, 0)).intValue();

            jTextFieldIntervalo.setText(String.format("%d",y0));
        }
    }//GEN-LAST:event_jTableWeibullMouseReleased

    private void botonInsertar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertar
        try
        {
            int intervalo = Integer.parseInt(jTextFieldIntervalo.getText());
            double fallas = Double.parseDouble(jTextFieldTEF.getText());
            nIntervalos = Integer.parseInt(jTextFieldNIntervalos.getText());

            if(nIntervalos < intervalo)
            {
                jButtonInsertar.setEnabled(false);
                jButtonProcesar.setFocusPainted(true);
                JOptionPane.showMessageDialog(this, "Límite de observaciones alcanzado.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
            
            model.setValueAt(intervalo, intervalo - 1, 0);
            model.setValueAt(fallas, intervalo -1 ,1);
            
            if (jButtonSalvar.isEnabled() == false) intervalo++;
            
            jTextFieldIntervalo.setText(String.format("%d", intervalo));
            jTextFieldTEF.setText("");
            jButtonInsertar.transferFocus();

            if (intervalo > Integer.parseInt(jTextFieldNIntervalos.getText())) {
                JOptionPane.showMessageDialog(this, "Límite de observaciones alcanzado.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                jButtonProcesar.setEnabled(true);
                jButtonInsertar.setEnabled(false);
                jTextFieldTEF.setEnabled(false);
                jButtonEstimar.setEnabled(true);
                jButtonSalvar.transferFocus();
            }            
        }
        
        catch ( NumberFormatException e )
        {
            jTextFieldTEF.setText("");
            JOptionPane.showMessageDialog(this, "Debe insertar un valor.", "Error", JOptionPane.WARNING_MESSAGE);
            jButtonProcesar.transferFocusBackward();
        }
}//GEN-LAST:event_botonInsertar

    private void botonModificar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificar
        if (model.getValueAt(0, 0)==null)
        {
            JOptionPane.showMessageDialog(this, "Debe haber minimo una fila " +
                    "llena en la tabla.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        jButtonSalvar.setEnabled(true);
        jButtonModificar.setEnabled(false);
        jTextFieldTEF.setEnabled(true);
        jButtonModificarI.setEnabled(false);
        jButtonSiguiente.setEnabled(false);
        jButtonEstimar.setEnabled(true);
        jButtonCalcular.setEnabled(true);
        
        if (jButtonInsertar.isEnabled()==false)
            jButtonInsertar.setEnabled(true);

        if (jButtonProcesar.isEnabled()==false)
            jButtonProcesar.setEnabled(true);

        jTextFieldBeta.setEditable(true);
        jTextFieldEscala.setEditable(true);
        jTextFieldPosicion.setEditable(true);
        jButtonCargarP.setEnabled(true);
        jTextFieldT1.setEditable(true);
        jTextFieldT2.setEditable(true);
        jTextFieldT3.setEditable(true);
        control1 = Integer.parseInt(jTextFieldIntervalo.getText());
        jTextFieldTEF.setText("");
        jButtonModificar.transferFocus();
    }//GEN-LAST:event_botonModificar

    private void botonSalvar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalvar
        if (jButtonProcesar.isEnabled()==true)
        {
            JOptionPane.showMessageDialog(this, "Antes de salvar debe procesar los datos.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (control1 > nIntervalos)
            jButtonInsertar.setEnabled(false);
        
        jTextFieldIntervalo.setText(String.format("%d",control1));
        jButtonModificar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonModificarI.setEnabled(true);
        jButtonSiguiente.setEnabled(true);
    }//GEN-LAST:event_botonSalvar

    private void botonProcesar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProcesar

        double [] arreglo = new double [jTableWeibull.getRowCount()];
        double [] arregloB = new double [jTableWeibull.getRowCount()];

        NumberFormat F = numberFormatterObj;

        fallac_w = new double [jTableWeibull.getRowCount()];
        fallac_w = gestor.fallaAcumulada(jTableWeibull.getRowCount());

        for (int i = 0; i<jTableWeibull.getRowCount(); i++)
            arreglo[i] = (Double) model.getValueAt(i, 1);
        arregloB = gestor.Ordenar(arreglo);

        setupNumberFmtObj(4);
        
        for (int i = 0; i<jTableWeibull.getRowCount(); i++)
        {
            model.setValueAt(Double.parseDouble(F.format(fallac_w[i]).replace(",", ".")), i, 2);
            model.setValueAt(Double.parseDouble(F.format(fallac_w[i] * 100).replace(",", ".")), i, 3);
            model.setValueAt(Double.parseDouble(F.format(arregloB[i]).replace(",", ".")), i, 1);
        }

        if (jButtonSalvar.isEnabled()==false)
            jButtonSiguiente.setEnabled(true);

        int intervalo = 1;
        double tef;
        double fallaAc;

        results = new ArrayList<DatosWeibull>();

        while (intervalo <= model.getRowCount())
        {
            tef = (Double) model.getValueAt(intervalo-1, 1);
            fallaAc = (Double) model.getValueAt(intervalo-1, 2);
            results.add(new DatosWeibull(intervalo, tef, fallaAc));
            intervalo++;
        }

        if (jTableWeibull.getColumnCount()>4)
            for (int i=0; i<jTableWeibull.getRowCount();i++)
            jTableWeibull.setValueAt(Double.parseDouble(F.format((Double)
                    jTableWeibull.getValueAt(i, 1)- Double.parseDouble(jTextFieldPosicion.getText())).replace(",", ".")), i, 4);

        gestor.ProcesarDatos(results);
        jButtonProcesar.setEnabled(false);
        jButtonProcesar.transferFocus();
    }//GEN-LAST:event_botonProcesar

    private void botonSalir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalir
        dispose();
}//GEN-LAST:event_botonSalir

    private void botonSiguiente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguiente
        if (jButtonCargarP.isEnabled()==true)
        {
            JOptionPane.showMessageDialog(this, "Debe cargar los parámetros antes de" +
                    "proceder a la siguiente interrfaz", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try
        {
            gestor.showWeibullCalIU();
            dispose();
        }

        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "Error: "+ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        catch (ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, "Error: "+ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        catch (FileNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, "Error: "+ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonSiguiente

    private void botonCargarP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarP
        String query, eliminar;
        try
        {
            double beta = Double.parseDouble(jTextFieldBeta.getText());
            double escala = Double.parseDouble(jTextFieldEscala.getText());
            double gamma = Double.parseDouble(jTextFieldPosicion.getText());
            if (beta>6.9 || beta<0.2)
            {
                JOptionPane.showMessageDialog(this, "Forma(β) debe ser un valor" +
                        " entre 0.2 y 6.9", "Error.", JOptionPane.WARNING_MESSAGE);
                return;
            }

            gestor.CargarParametros(beta, escala, gamma);

            jTextFieldBeta.setEditable(false);
            jTextFieldEscala.setEditable(false);
            jTextFieldPosicion.setEditable(false);
            jButtonCargarP.setEnabled(false);
            jButtonCargarP.transferFocus();
        }

        catch ( NumberFormatException e )
        {
            jTextFieldTEF.setText("");
            JOptionPane.showMessageDialog(this, "Debe insertar un valor.", "Error", JOptionPane.WARNING_MESSAGE);
            jTextFieldEscala.transferFocusBackward();
        }
    }//GEN-LAST:event_botonCargarP

    private void jTextFieldBetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBetaKeyTyped
       gestor.validacionCampoChar(evt, "[.0-9]");
       gestor.validarTamaño(jTextFieldBeta.getText(), 4, evt);
    }//GEN-LAST:event_jTextFieldBetaKeyTyped

    private void jTextFieldEscalaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEscalaKeyTyped
        gestor.validacionCampoChar(evt, "[.0-9]");
        gestor.validarTamaño(jTextFieldEscala.getText(), 8, evt);
    }//GEN-LAST:event_jTextFieldEscalaKeyTyped

    private void jTextFieldPosicionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPosicionKeyTyped
        gestor.validacionCampoChar(evt, "[.0-9]");
        gestor.validarTamaño(jTextFieldPosicion.getText(), 8, evt);
    }//GEN-LAST:event_jTextFieldPosicionKeyTyped

    private void jTextFieldBetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBetaActionPerformed
        jTextFieldBeta.transferFocus();
    }//GEN-LAST:event_jTextFieldBetaActionPerformed

    private void jTextFieldEscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEscalaActionPerformed
        jTextFieldEscala.transferFocus();
    }//GEN-LAST:event_jTextFieldEscalaActionPerformed

    private void jTextFieldPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPosicionActionPerformed
        jTextFieldPosicion.transferFocus();
    }//GEN-LAST:event_jTextFieldPosicionActionPerformed

    private void jTextFieldT1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldT1KeyTyped
        gestor.validacionCampoChar(evt, "[.0-9]");
        gestor.validarTamaño(jTextFieldT1.getText(), 8, evt);
    }//GEN-LAST:event_jTextFieldT1KeyTyped

    private void jTextFieldT2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldT2KeyTyped
        gestor.validacionCampoChar(evt, "[.0-9]");
        gestor.validarTamaño(jTextFieldT2.getText(), 8, evt);
    }//GEN-LAST:event_jTextFieldT2KeyTyped

    private void jTextFieldT3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldT3KeyTyped
        gestor.validacionCampoChar(evt, "[.0-9]");
        gestor.validarTamaño(jTextFieldT3.getText(), 8, evt);
    }//GEN-LAST:event_jTextFieldT3KeyTyped

    private void jTextFieldT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldT1ActionPerformed
        jTextFieldT1.transferFocus();
    }//GEN-LAST:event_jTextFieldT1ActionPerformed

    private void jTextFieldT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldT2ActionPerformed
        jTextFieldT2.transferFocus();
    }//GEN-LAST:event_jTextFieldT2ActionPerformed

    private void jTextFieldT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldT3ActionPerformed
        jTextFieldT3.transferFocus();
    }//GEN-LAST:event_jTextFieldT3ActionPerformed

    private void botonCalcular(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcular
        try
        {
            double t1 = Double.parseDouble(jTextFieldT1.getText());
            double t2 = Double.parseDouble(jTextFieldT2.getText());
            double t3 = Double.parseDouble(jTextFieldT3.getText());

            if (t1>t2 || t2>t3)
            {
                JOptionPane.showMessageDialog(this, "Debe t1 debe ser menor que t2 y t2" +
                        " debe ser menor que t3.", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            double gamma;

            gamma = ((t2*t2) - (t1*t3))/((2*t2)-t1-t3);

            NumberFormat F = numberFormatterObj;
            setupNumberFmtObj(2);
        
            jTextFieldPosicion.setText(F.format(gamma).replace(",","."));

            if (jTableWeibull.getColumnCount()<5)
            {
                model.addColumn("T.E.F.-γ");
                jTableWeibull.setModel(model);
            }

            for (int i=0; i<jTableWeibull.getRowCount();i++)
                jTableWeibull.setValueAt(Double.parseDouble(F.format((Double)
                        jTableWeibull.getValueAt(i, 1)-gamma).replace(",", ".")), i, 4);

            jButtonCalcular.setEnabled(false);

            if (jButtonCargarP.isEnabled()==false)
                jButtonCargarP.setEnabled(true);

            jTextFieldT1.setEditable(false);
            jTextFieldT2.setEditable(false);
            jTextFieldT3.setEditable(false);
        }

        catch ( NumberFormatException e )
        {
            jTextFieldTEF.setText("");
            JOptionPane.showMessageDialog(this, "Debe insertar valores para todos los campos.", "Error", JOptionPane.WARNING_MESSAGE);
            jTextFieldEscala.transferFocusBackward();
        }
    }//GEN-LAST:event_botonCalcular

    private void botonEstimar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEstimar
       double arreglo []= new double[jTableWeibull.getRowCount()];
       int l=0;

        if (jButtonProcesar.isEnabled()==true)
       {
           JOptionPane.showMessageDialog(this, "Antes de estimar los parámetros debe procesar los datos.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
           return;
       }

       double tef[] = new double[jTableWeibull.getRowCount()];
       double xmedian = gestor.CalX(jTableWeibull.getRowCount());
       
       if (jTableWeibull.getColumnCount()>4)
           for (int j = 0; j < jTableWeibull.getRowCount(); j++)
               tef[j]=(Double)jTableWeibull.getValueAt(j,4);
       else
           for (int j = 0; j < jTableWeibull.getRowCount(); j++)
               tef[j]=(Double)jTableWeibull.getValueAt(j,1);

       for(l=0; l < jTableWeibull.getRowCount();l++)
           arreglo[l] =(Double)jTableWeibull.getValueAt(l,1);
       
       double ymedian = gestor.CalY(tef, jTableWeibull.getRowCount());
       double betaEst = gestor.CalBeta(jTableWeibull.getRowCount(), tef);
       double escalaEst = gestor.CalEscala(ymedian, xmedian, betaEst);
       double posicion = gestor.Estimar(arreglo);
              
       NumberFormat F = numberFormatterObj;

       setupNumberFmtObj(2);
       jTextFieldBeta.setText(F.format(betaEst).replace(",", "."));
       jTextFieldEscala.setText(F.format(escalaEst).replace(",", "."));
       jTextFieldPosicion.setText(F.format(
       jButtonEstimar.setEnabled(false);
    }//GEN-LAST:event_botonEstimar

    protected void setupNumberFmtObj(int k)
    {
        String patron = "0.";
        for (int j=0; j<k; j++)
            patron = patron + "#";
        if (this.numberFormatterObj instanceof DecimalFormat) {
            ((DecimalFormat) this.numberFormatterObj).applyPattern(patron);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonCancelarI;
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JButton jButtonCargarP;
    private javax.swing.JButton jButtonEstimar;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonModificarI;
    private javax.swing.JButton jButtonProcesar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelBeta;
    private javax.swing.JLabel jLabelEscala;
    private javax.swing.JLabel jLabelIntervalo;
    private javax.swing.JLabel jLabelNDias;
    private javax.swing.JLabel jLabelNFallas;
    private javax.swing.JLabel jLabelPosicion;
    private javax.swing.JLabel jLabelT1;
    private javax.swing.JLabel jLabelT2;
    private javax.swing.JLabel jLabelT3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableWeibull;
    private javax.swing.JTextField jTextFieldBeta;
    private javax.swing.JTextField jTextFieldEscala;
    private javax.swing.JTextField jTextFieldIntervalo;
    private javax.swing.JTextField jTextFieldNIntervalos;
    private javax.swing.JTextField jTextFieldPosicion;
    private javax.swing.JTextField jTextFieldT1;
    private javax.swing.JTextField jTextFieldT2;
    private javax.swing.JTextField jTextFieldT3;
    private javax.swing.JTextField jTextFieldTEF;
    // End of variables declaration//GEN-END:variables

}
